### PR TITLE
recognize error on creating floating ip when ext_network not given

### PR DESCRIPTION
**Pull request by kgawda**

### CODE REVIEW

**Comment by EarthmanT** [comment]
Can you squash these commits into 1 commit?

**Comment by kgawda** [comment]
here you are, squashed

**Comment by EarthmanT** [comment]
I'll merge it soon. The guy who wrote it is making some structural changes
to the repo and I don't want to cause conflicts with his master. (I don't
know if he rebases before merging or not.) After he writes me that it's
updated, I'll merge.

**Comment by EarthmanT** [comment]
I think the indentation needs to be fixed

**Comment by kgawda** [comment]
the indentation is main point in this commit - NonRecoverableError should be raised if floating_network_id is not in floatingip **and** ext_network evaluates to false. Otherwise OpenStack returns error.

**Pull request merged**
