### PR TITLE
allow resource id input to operations

### PR DESCRIPTION
**Pull request by EarthmanT**

### CODE REVIEW

**Comment by EarthmanT** [comment]
#231

**Comment by bjgill** [comment]
Thanks for the rapidity. My testing suggests that there may be a problem, however. I get the error message:

```
$ cfy blueprint upload --validate test-blueprint.yaml 
Validating blueprint: test-blueprint.yaml
SELF can only be used in a context of node template but appears in node_template_relationship.
```

With blueprint (taken from https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/master/docs/examples.rst#example-i):

```yaml
tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.3.1/types.yaml
  - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-openstack-plugin/236-add-resource-id-input/plugin.yaml

inputs:

  username:
    type: string

  keystone_password:
    type: string

  tenant_name:
    type: string

  auth_url:
    type: string

  region:
    type: string

  network_id:
    type: string

  subnet_id:
    type: string

dsl_definitions:

  openstack_config: &openstack_config
    username: { get_input: username }
    password: { get_input: keystone_password }
    tenant_name: { get_input: tenant_name }
    auth_url: { get_input: auth_url }
    region: { get_input: region }

node_templates:

  my_floating_ip:
    type: cloudify.openstack.nodes.FloatingIP
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            args:
              floating_network_name: Ext-Net

  my_server:
    type: cloudify.openstack.nodes.Server
    properties:
      resource_id: my_server_openstack_name
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            args:
              image: 8672f4c6-e33d-46f5-b6d8-ebbeba12fa02
              flavor: 101
      cloudify.interfaces.validation:
        creation:
          inputs:
            args:
              image: 8672f4c6-e33d-46f5-b6d8-ebbeba12fa02
              flavor: 101
    relationships:
      - target: my_floating_ip
        type: cloudify.openstack.server_connected_to_floating_ip
```

**Comment by EarthmanT** [comment]
@bjgill OK. I have fixed this issue. We will run some tests and release it.

**Comment by EarthmanT** [comment]
@bjgill merged released: https://github.com/cloudify-cosmo/cloudify-openstack-plugin/releases/tag/2.8.0

**Pull request merged**
