### PR TITLE
OPENSTACK-94 upgrade nova to 2.29

### PR DESCRIPTION
**Pull request by funkyHat**
JIRA: OPENSTACK-94

### CODE REVIEW

**Comment by funkyHat** [comment]
Fixes the immediate issue but causes `python-novaclient` to complain about the way we're instantiating the `Client` class.
That's not a simple to fix because of all the `ClientWithSugar` inheritance stuff. More discussion required but I think for now correct behaviout with the warnings is better than broken features

**Comment by idanmo** [comment]
This should probably go to 2.0-build ?

**Comment by geokala** [comment]
Needs flake8 happiness. Reviewing the code now.

**Comment by funkyHat** [comment]
Yep... had to fix the same in the other PR too :)

**Comment by funkyHat** [comment]
Actually tbh if we're going to merge PR #123 this PR is obsolete

**Pull request closed without merging**
